/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI.ManagerWorkArea;

import AppSystem.AppSystem;
import AppSystem.UserAccount;
import UI.MainJFrame;

/**
 *
 * @author Panzi
 */
public class ManagerJFrame extends javax.swing.JFrame {

    private AppSystem appSystem;
    private UserAccount userAccount;
    /**
     * Creates new form ManagerJFrame
     */
    public ManagerJFrame() {
        initComponents();
    }

    public ManagerJFrame(AppSystem appSystem, UserAccount userAccount) {
        initComponents();
        this.setVisible(true);
        
        this.appSystem = appSystem;
        this.userAccount = userAccount;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        btnCustomerManage = new javax.swing.JButton();
        btnLibrarianManage = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton4.setText("LOGOUT");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));

        btnCustomerManage.setText("CUSTOMERS");
        btnCustomerManage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCustomerManageActionPerformed(evt);
            }
        });
        jPanel1.add(btnCustomerManage, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 20, -1, -1));

        btnLibrarianManage.setText("LIBRARIAN");
        btnLibrarianManage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLibrarianManageActionPerformed(evt);
            }
        });
        jPanel1.add(btnLibrarianManage, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 20, -1, -1));

        jSplitPane1.setTopComponent(jPanel1);

        getContentPane().add(jSplitPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new MainJFrame(this.appSystem, this.userAccount);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void btnCustomerManageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCustomerManageActionPerformed
        // TODO add your handling code here:
        jSplitPane1.setRightComponent(new CustomerManagementJPanel(appSystem,userAccount));
    }//GEN-LAST:event_btnCustomerManageActionPerformed

    private void btnLibrarianManageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLibrarianManageActionPerformed
        // TODO add your handling code here:
        jSplitPane1.setRightComponent(new LibrarianManagementJPanel(appSystem,userAccount));
    }//GEN-LAST:event_btnLibrarianManageActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManagerJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManagerJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManagerJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManagerJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManagerJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCustomerManage;
    private javax.swing.JButton btnLibrarianManage;
    private javax.swing.JButton jButton4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSplitPane jSplitPane1;
    // End of variables declaration//GEN-END:variables
}
