/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import Model.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Panzi
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    private Person person;
    public MainFrame() {
        initComponents();
        this.person = new Person();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        SaveBtn = new javax.swing.JButton();
        fieldFirstName = new javax.swing.JTextField();
        fieldCurStreet = new javax.swing.JTextField();
        LabelFirstName = new javax.swing.JLabel();
        LabelStreet = new javax.swing.JLabel();
        fieldNUID = new javax.swing.JTextField();
        LabelNUID = new javax.swing.JLabel();
        fieldLastName = new javax.swing.JTextField();
        LabelLastName = new javax.swing.JLabel();
        fieldCollegeName = new javax.swing.JTextField();
        LabelCollegeName = new javax.swing.JLabel();
        fieldOfficePhone = new javax.swing.JTextField();
        LabelOfficePhone = new javax.swing.JLabel();
        fieldOfficeEmailID = new javax.swing.JTextField();
        LabelOfficeEmail = new javax.swing.JLabel();
        fieldCurAPT_NO = new javax.swing.JTextField();
        LabelAPT_NO = new javax.swing.JLabel();
        fieldCurCity_State = new javax.swing.JTextField();
        LabelCity_State = new javax.swing.JLabel();
        fieldCurZipCode = new javax.swing.JTextField();
        LabelZipCode = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        fieldPersonalPhone = new javax.swing.JTextField();
        fieldPersonalEmail = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        LabelPersonalPhone = new javax.swing.JLabel();
        LabelPersonalEmail = new javax.swing.JLabel();
        LabelPStreet = new javax.swing.JLabel();
        fieldPermanentStreet = new javax.swing.JTextField();
        fieldPermanentAptNo = new javax.swing.JTextField();
        fieldPermanentCity_State = new javax.swing.JTextField();
        fieldPermanentZipCode = new javax.swing.JTextField();
        LabelPZipCode = new javax.swing.JLabel();
        LabelPCity_State = new javax.swing.JLabel();
        LabelPAPT_NO = new javax.swing.JLabel();
        ViewFrame = new javax.swing.JPanel();
        ViewFirstName = new javax.swing.JLabel();
        ViewCurStreet = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        ViewNUID = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ViewLastName = new javax.swing.JLabel();
        ViewCollegeName = new javax.swing.JLabel();
        ViewOfficePhone = new javax.swing.JLabel();
        ViewOfficeEmail = new javax.swing.JLabel();
        ViewCurAptNo = new javax.swing.JLabel();
        ViewCurCity_State = new javax.swing.JLabel();
        ViewCurZipCode = new javax.swing.JLabel();
        ViewPersonalPhone = new javax.swing.JLabel();
        ViewPersonalEmail = new javax.swing.JLabel();
        ViewPerAptNo = new javax.swing.JLabel();
        ViewPerStreet = new javax.swing.JLabel();
        ViewPerCity_State = new javax.swing.JLabel();
        ViewPerZipCode = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        SaveBtn.setFont(new java.awt.Font("微软雅黑", 1, 18)); // NOI18N
        SaveBtn.setText("SAVE");
        SaveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveBtnActionPerformed(evt);
            }
        });

        fieldFirstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldFirstNameActionPerformed(evt);
            }
        });

        fieldCurStreet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldCurStreetActionPerformed(evt);
            }
        });

        LabelFirstName.setText("First Name");

        LabelStreet.setText("Street");

        LabelNUID.setText("NUID");

        fieldLastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldLastNameActionPerformed(evt);
            }
        });

        LabelLastName.setText("Last Name");

        LabelCollegeName.setText("College Name");

        LabelOfficePhone.setText("Phone");

        LabelOfficeEmail.setText("Email ID");

        LabelAPT_NO.setText("APT_NO");

        fieldCurCity_State.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldCurCity_StateActionPerformed(evt);
            }
        });

        LabelCity_State.setText("City/State");

        LabelZipCode.setText("ZipCode");

        jLabel4.setBackground(new java.awt.Color(255, 51, 102));
        jLabel4.setFont(new java.awt.Font("微软雅黑", 1, 18)); // NOI18N
        jLabel4.setText("Personal Contact");

        jLabel5.setBackground(new java.awt.Color(51, 51, 51));
        jLabel5.setFont(new java.awt.Font("微软雅黑", 3, 24)); // NOI18N
        jLabel5.setText("Student's Information");

        jLabel6.setBackground(new java.awt.Color(255, 255, 0));
        jLabel6.setFont(new java.awt.Font("微软雅黑", 1, 18)); // NOI18N
        jLabel6.setText("Office Contact");

        jLabel7.setBackground(new java.awt.Color(51, 255, 0));
        jLabel7.setFont(new java.awt.Font("微软雅黑", 1, 18)); // NOI18N
        jLabel7.setText("Current Address");

        jLabel8.setBackground(new java.awt.Color(255, 0, 255));
        jLabel8.setFont(new java.awt.Font("微软雅黑", 1, 18)); // NOI18N
        jLabel8.setText("Permanent Address");

        LabelPersonalPhone.setText("Phone");

        LabelPersonalEmail.setText("Email ID");

        LabelPStreet.setText("Street");

        fieldPermanentCity_State.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldPermanentCity_StateActionPerformed(evt);
            }
        });

        LabelPZipCode.setText("ZipCode");

        LabelPCity_State.setText("City/State");

        LabelPAPT_NO.setText("APT_NO");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(181, 181, 181))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(224, 224, 224))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelPAPT_NO)
                            .addComponent(LabelFirstName)
                            .addComponent(LabelNUID)
                            .addComponent(LabelPersonalPhone))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGap(129, 129, 129)
                                        .addComponent(jLabel6)
                                        .addGap(75, 75, 75))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(LabelOfficeEmail)
                                                    .addComponent(jLabel4)
                                                    .addComponent(LabelPersonalEmail))
                                                .addGap(36, 36, 36))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(fieldFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(fieldNUID, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(LabelCollegeName)
                                                    .addComponent(LabelLastName))))
                                        .addGap(18, 18, 18)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(fieldCollegeName, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(fieldLastName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(fieldOfficeEmailID, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(fieldPersonalEmail, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(LabelPZipCode)
                                        .addGap(18, 18, 18)
                                        .addComponent(fieldPermanentZipCode, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(fieldPermanentStreet, javax.swing.GroupLayout.PREFERRED_SIZE, 486, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(130, 130, 130)
                                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(LabelZipCode)
                                            .addGap(18, 18, 18)
                                            .addComponent(fieldCurZipCode, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(23, 23, 23))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(LabelAPT_NO)
                                .addGap(18, 18, 18)
                                .addComponent(fieldCurAPT_NO, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(LabelCity_State)
                                .addGap(18, 18, 18)
                                .addComponent(fieldCurCity_State, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(LabelStreet)
                                .addGap(25, 25, 25)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(fieldPermanentAptNo, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(LabelPCity_State)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(fieldPermanentCity_State, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(fieldCurStreet, javax.swing.GroupLayout.PREFERRED_SIZE, 485, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(LabelPStreet))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(273, 273, 273)
                        .addComponent(SaveBtn))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(LabelOfficePhone)
                        .addGap(42, 42, 42)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fieldPersonalPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fieldOfficePhone, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldNUID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelNUID)
                    .addComponent(LabelCollegeName)
                    .addComponent(fieldCollegeName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelFirstName)
                    .addComponent(fieldLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelLastName))
                .addGap(25, 25, 25)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelOfficePhone)
                    .addComponent(fieldOfficePhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelOfficeEmail)
                    .addComponent(fieldOfficeEmailID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldPersonalPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldPersonalEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelPersonalPhone)
                    .addComponent(LabelPersonalEmail))
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldCurStreet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelStreet))
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldCurAPT_NO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelZipCode)
                    .addComponent(fieldCurZipCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelAPT_NO)
                    .addComponent(LabelCity_State)
                    .addComponent(fieldCurCity_State, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelPStreet)
                    .addComponent(fieldPermanentStreet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldPermanentAptNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldPermanentCity_State, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldPermanentZipCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelPZipCode)
                    .addComponent(LabelPCity_State)
                    .addComponent(LabelPAPT_NO))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(SaveBtn)
                .addGap(23, 23, 23))
        );

        jSplitPane1.setLeftComponent(jPanel1);

        ViewFrame.setBackground(new java.awt.Color(204, 255, 204));
        ViewFrame.setPreferredSize(new java.awt.Dimension(700, 714));

        ViewFirstName.setBackground(new java.awt.Color(255, 204, 204));
        ViewFirstName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        ViewCurStreet.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel3.setFont(new java.awt.Font("宋体", 1, 18)); // NOI18N
        jLabel3.setText("First Name");

        jLabel1.setFont(new java.awt.Font("宋体", 1, 18)); // NOI18N
        jLabel1.setText("Permanent Street Name");

        ViewNUID.setText(" ");
        ViewNUID.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setFont(new java.awt.Font("宋体", 1, 18)); // NOI18N
        jLabel2.setText("NUID");

        ViewLastName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        ViewCollegeName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        ViewOfficePhone.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        ViewOfficeEmail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        ViewCurAptNo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        ViewCurCity_State.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        ViewCurZipCode.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        ViewPersonalPhone.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        ViewPersonalEmail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        ViewPerAptNo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        ViewPerStreet.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        ViewPerCity_State.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        ViewPerZipCode.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel15.setFont(new java.awt.Font("宋体", 1, 18)); // NOI18N
        jLabel15.setText("Last Name");

        jLabel16.setFont(new java.awt.Font("宋体", 1, 18)); // NOI18N
        jLabel16.setText("College Name");

        jLabel17.setFont(new java.awt.Font("宋体", 1, 18)); // NOI18N
        jLabel17.setText("Office Phone");

        jLabel18.setFont(new java.awt.Font("宋体", 1, 18)); // NOI18N
        jLabel18.setText("Office Email");

        jLabel19.setFont(new java.awt.Font("宋体", 1, 18)); // NOI18N
        jLabel19.setText("Personal Phone");

        jLabel20.setFont(new java.awt.Font("宋体", 1, 18)); // NOI18N
        jLabel20.setText("Personal Email");

        jLabel21.setFont(new java.awt.Font("宋体", 1, 18)); // NOI18N
        jLabel21.setText("Cur Street Name");

        jLabel22.setFont(new java.awt.Font("宋体", 1, 18)); // NOI18N
        jLabel22.setText("Cur Apt. No");

        jLabel23.setFont(new java.awt.Font("宋体", 1, 18)); // NOI18N
        jLabel23.setText("Cur City/State");

        jLabel24.setFont(new java.awt.Font("宋体", 1, 18)); // NOI18N
        jLabel24.setText("Cur ZipCode");

        jLabel25.setFont(new java.awt.Font("宋体", 1, 18)); // NOI18N
        jLabel25.setText("Permanent Apt. No");

        jLabel26.setFont(new java.awt.Font("宋体", 1, 18)); // NOI18N
        jLabel26.setText("Permanent City/State");

        jLabel27.setFont(new java.awt.Font("宋体", 1, 18)); // NOI18N
        jLabel27.setText("Permanent ZipCode");

        javax.swing.GroupLayout ViewFrameLayout = new javax.swing.GroupLayout(ViewFrame);
        ViewFrame.setLayout(ViewFrameLayout);
        ViewFrameLayout.setHorizontalGroup(
            ViewFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ViewFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ViewFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19)
                    .addComponent(jLabel20)
                    .addComponent(jLabel21)
                    .addComponent(jLabel22)
                    .addComponent(jLabel25)
                    .addComponent(jLabel26)
                    .addComponent(jLabel27)
                    .addComponent(jLabel24)
                    .addComponent(jLabel23)
                    .addComponent(jLabel1))
                .addGap(32, 32, 32)
                .addGroup(ViewFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(ViewFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(ViewPerStreet, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ViewCurCity_State, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(ViewFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ViewPerZipCode, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ViewPerCity_State, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(ViewFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(ViewPersonalPhone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ViewOfficeEmail, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ViewOfficePhone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ViewNUID, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
                                .addComponent(ViewLastName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ViewCollegeName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ViewFirstName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ViewPersonalEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ViewCurStreet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ViewCurAptNo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ViewCurZipCode, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addComponent(ViewPerAptNo, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 205, Short.MAX_VALUE))
        );
        ViewFrameLayout.setVerticalGroup(
            ViewFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ViewFrameLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(ViewFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(ViewNUID, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(ViewFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(ViewFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(ViewFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ViewFrameLayout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel16))
                    .addGroup(ViewFrameLayout.createSequentialGroup()
                        .addComponent(ViewLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ViewCollegeName, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(24, 24, 24)
                .addGroup(ViewFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ViewOfficePhone, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(ViewFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ViewFrameLayout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel19))
                    .addGroup(ViewFrameLayout.createSequentialGroup()
                        .addComponent(ViewOfficeEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ViewPersonalPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(ViewFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ViewFrameLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel20))
                    .addGroup(ViewFrameLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(ViewPersonalEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(41, 41, 41)
                .addGroup(ViewFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel21)
                    .addComponent(ViewCurStreet, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(ViewFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ViewCurAptNo, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22))
                .addGroup(ViewFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ViewFrameLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel23))
                    .addGroup(ViewFrameLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(ViewCurCity_State, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(40, 40, 40)
                .addGroup(ViewFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ViewCurZipCode, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24))
                .addGap(23, 23, 23)
                .addGroup(ViewFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(ViewPerStreet, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(ViewFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel25)
                    .addComponent(ViewPerAptNo, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(ViewFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(ViewFrameLayout.createSequentialGroup()
                        .addComponent(jLabel26)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel27))
                    .addGroup(ViewFrameLayout.createSequentialGroup()
                        .addComponent(ViewPerCity_State, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)
                        .addComponent(ViewPerZipCode, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jSplitPane1.setRightComponent(ViewFrame);

        getContentPane().add(jSplitPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SaveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveBtnActionPerformed
             // TODO add your handling code here:
        String nuid = fieldNUID.getText();
        String firstName = fieldFirstName.getText();
        String lastName = fieldLastName.getText();
        String CollegeName = fieldCollegeName.getText();
        this.person.setNUID(nuid);
        this.person.setFirstName(firstName);
        this.person.setLastName(lastName);
        this.person.setCollegeName(CollegeName);
       
        long officePhone = Long.parseLong(fieldOfficePhone.getText());
        String officeEmail = fieldOfficeEmailID.getText();
        long personalPhone = Long.parseLong(fieldPersonalPhone.getText());
        String personalEmail = fieldPersonalEmail.getText();

        Contact officeContact = this.person.getOfficeContact();
        officeContact.setPhone(officePhone);
        officeContact.setEmail_ID(officeEmail);
        Contact personalContact = this.person.getPersonalContact();
        personalContact.setPhone(personalPhone);
        personalContact.setEmail_ID(personalEmail);

        String curStreet = fieldCurStreet.getText();
        int curAptId = Integer.parseInt(fieldCurAPT_NO.getText());
        String curCity_State = fieldCurCity_State.getText();
        String curZipCode = fieldCurZipCode.getText();
        String perStreet = fieldPermanentStreet.getText();
        int perAptId = Integer.parseInt(fieldPermanentAptNo.getText());
        String perCity_State = fieldPermanentCity_State.getText();
        String perZipCode = fieldPermanentZipCode.getText();        

        Address curAddress = this.person.getCurAddress();
        curAddress.setStreetName(curStreet);
        curAddress.setApt_No(curAptId);
        curAddress.setCity_State(curCity_State);
        curAddress.setZipCode(curZipCode);
        Address perAddress = this.person.getPerAddress();
        perAddress.setStreetName(perStreet);
        perAddress.setApt_No(perAptId);
        perAddress.setCity_State(perCity_State);
        perAddress.setZipCode(perZipCode);

        JOptionPane.showMessageDialog(null, "SAVED SUCCESSFULLLY!");
        display();

    }//GEN-LAST:event_SaveBtnActionPerformed

    public void display(){
//       Person obj2 = new Person();
       ViewNUID.setText(this.person.getNUID());
       ViewFirstName.setText(this.person.getFirstName());
       ViewLastName.setText(this.person.getLastName());
       ViewCollegeName.setText(this.person.getCollegeName());

       ViewOfficePhone.setText(String.valueOf(this.person.getOfficeContact().getPhone()));
       ViewOfficeEmail.setText(this.person.getOfficeContact().getEmail_ID());
       ViewPersonalPhone.setText(String.valueOf(this.person.getPersonalContact().getPhone()));
       ViewPersonalEmail.setText(this.person.getPersonalContact().getEmail_ID());

       ViewCurStreet.setText(this.person.getCurAddress().getStreetName());
       ViewCurAptNo.setText(String.valueOf(this.person.getCurAddress().getApt_No()));
       ViewCurCity_State.setText(this.person.getCurAddress().getCity_State());
       ViewCurZipCode.setText(this.person.getCurAddress().getZipCode());

       ViewPerStreet.setText(this.person.getPerAddress().getStreetName());
       ViewPerAptNo.setText(String.valueOf(this.person.getPerAddress().getApt_No()));
       ViewPerCity_State.setText(this.person.getPerAddress().getCity_State());
       ViewPerZipCode.setText(this.person.getPerAddress().getZipCode());
    }


    private void fieldCurStreetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldCurStreetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldCurStreetActionPerformed

    private void fieldFirstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldFirstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldFirstNameActionPerformed

    private void fieldLastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldLastNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldLastNameActionPerformed

    private void fieldCurCity_StateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldCurCity_StateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldCurCity_StateActionPerformed

    private void fieldPermanentCity_StateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldPermanentCity_StateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldPermanentCity_StateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelAPT_NO;
    private javax.swing.JLabel LabelCity_State;
    private javax.swing.JLabel LabelCollegeName;
    private javax.swing.JLabel LabelFirstName;
    private javax.swing.JLabel LabelLastName;
    private javax.swing.JLabel LabelNUID;
    private javax.swing.JLabel LabelOfficeEmail;
    private javax.swing.JLabel LabelOfficePhone;
    private javax.swing.JLabel LabelPAPT_NO;
    private javax.swing.JLabel LabelPCity_State;
    private javax.swing.JLabel LabelPStreet;
    private javax.swing.JLabel LabelPZipCode;
    private javax.swing.JLabel LabelPersonalEmail;
    private javax.swing.JLabel LabelPersonalPhone;
    private javax.swing.JLabel LabelStreet;
    private javax.swing.JLabel LabelZipCode;
    private javax.swing.JButton SaveBtn;
    private javax.swing.JLabel ViewCollegeName;
    private javax.swing.JLabel ViewCurAptNo;
    private javax.swing.JLabel ViewCurCity_State;
    private javax.swing.JLabel ViewCurStreet;
    private javax.swing.JLabel ViewCurZipCode;
    private javax.swing.JLabel ViewFirstName;
    private javax.swing.JPanel ViewFrame;
    private javax.swing.JLabel ViewLastName;
    private javax.swing.JLabel ViewNUID;
    private javax.swing.JLabel ViewOfficeEmail;
    private javax.swing.JLabel ViewOfficePhone;
    private javax.swing.JLabel ViewPerAptNo;
    private javax.swing.JLabel ViewPerCity_State;
    private javax.swing.JLabel ViewPerStreet;
    private javax.swing.JLabel ViewPerZipCode;
    private javax.swing.JLabel ViewPersonalEmail;
    private javax.swing.JLabel ViewPersonalPhone;
    private javax.swing.JTextField fieldCollegeName;
    private javax.swing.JTextField fieldCurAPT_NO;
    private javax.swing.JTextField fieldCurCity_State;
    private javax.swing.JTextField fieldCurStreet;
    private javax.swing.JTextField fieldCurZipCode;
    private javax.swing.JTextField fieldFirstName;
    private javax.swing.JTextField fieldLastName;
    private javax.swing.JTextField fieldNUID;
    private javax.swing.JTextField fieldOfficeEmailID;
    private javax.swing.JTextField fieldOfficePhone;
    private javax.swing.JTextField fieldPermanentAptNo;
    private javax.swing.JTextField fieldPermanentCity_State;
    private javax.swing.JTextField fieldPermanentStreet;
    private javax.swing.JTextField fieldPermanentZipCode;
    private javax.swing.JTextField fieldPersonalEmail;
    private javax.swing.JTextField fieldPersonalPhone;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSplitPane jSplitPane1;
    // End of variables declaration//GEN-END:variables
}
