/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;
import Model.Application;
import Model.VitalSignHistory;
import javax.swing.JOptionPane;
/**
 *
 * @author Panzi
 */
public class CreateJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateJPanel
     */
    private Application application;
    public CreateJPanel(Application application) {
        initComponents();
        this.application = application;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        fieldObservationID = new javax.swing.JTextField();
        fieldTemperature = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        fieldBloodPressure = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnAddObservation = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("宋体", 1, 24)); // NOI18N
        jLabel1.setText("CREATE A VITAL SIGN");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 60, -1, -1));

        jLabel2.setText("ID");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, -1, -1));
        add(fieldObservationID, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, 190, -1));
        add(fieldTemperature, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 240, 190, -1));

        jLabel3.setText("Temperature");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, -1, -1));
        add(fieldBloodPressure, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 340, 190, -1));

        jLabel4.setText("Blood Pressure");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, -1, -1));

        btnAddObservation.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        btnAddObservation.setText("ADD OBSERVATION");
        btnAddObservation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddObservationActionPerformed(evt);
            }
        });
        add(btnAddObservation, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 490, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddObservationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddObservationActionPerformed
        // TODO add your handling code here:
        //add an observation to history list
        VitalSignHistory history = this.application.getHistory();
        String id = fieldObservationID.getText();
        String temperature = fieldTemperature.getText();
        String bloodPressure = fieldBloodPressure.getText();
        if(history.checkObservationIdUnique(Integer.valueOf(id))){
           history.createObservation(Integer.valueOf(id), Double.valueOf(bloodPressure), Double.valueOf(temperature));

           JOptionPane.showMessageDialog(null, "Added observation!");
        }else{
           JOptionPane.showMessageDialog(null, "Observation ID is not unique!");
        }
        
    }//GEN-LAST:event_btnAddObservationActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddObservation;
    private javax.swing.JTextField fieldBloodPressure;
    private javax.swing.JTextField fieldObservationID;
    private javax.swing.JTextField fieldTemperature;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
