/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;
import Model.*;
import java.util.ArrayList;
import javax.swing.JLabel;
/**
 *
 * @author Panzi
 */
public class MedicineAssignJPanel extends javax.swing.JPanel {

    /**
     * Creates new form MedicineAssignJPanel
     */
    private Application application;
    public MedicineAssignJPanel(Application application) {
        initComponents();
        this.application = application;
        populateDropdowns();
    }


    public void populateDropdowns(){
        ArrayList<Medicine> medicines = this.application.getCatalog().getMedicineList();

        ArrayList<Observation> observations = this.application.getHistory().getVitalSignHistory();

        for(Observation o : observations){
           observationBox.addItem(o);
        }

        for(Medicine med : medicines){
           medicineBox.addItem(med);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        observationBox = new javax.swing.JComboBox();
        medicineBox = new javax.swing.JComboBox();
        btnAssign = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 255, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        observationBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                observationBoxItemStateChanged(evt);
            }
        });
        add(observationBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 200, 220, 50));

        add(medicineBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, 220, 50));

        btnAssign.setText("Assign");
        btnAssign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssignActionPerformed(evt);
            }
        });
        add(btnAssign, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 380, -1, -1));
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 310, 50, 30));

        jLabel2.setText("(cur medicine:)");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 320, -1, -1));

        jLabel3.setText("Medicine");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, -1, -1));

        jLabel4.setText("Observation");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 150, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnAssignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssignActionPerformed
        // TODO add your handling code here:
        Observation o = (Observation)observationBox.getSelectedItem();
        Medicine m = (Medicine) medicineBox.getSelectedItem();
        o.setMedication(m);
    }//GEN-LAST:event_btnAssignActionPerformed

    private void observationBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_observationBoxItemStateChanged
        // TODO add your handling code here:
        Observation o = (Observation)observationBox.getSelectedItem();
        if(o.getMedication() != null){
           jLabel1.setText(o.getMedication().getMedicineName());
        }
    }//GEN-LAST:event_observationBoxItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAssign;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JComboBox medicineBox;
    private javax.swing.JComboBox observationBox;
    // End of variables declaration//GEN-END:variables
}
