/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import Model.Customer;
import Model.DeliveryPackage;
import Model.Product;
import javax.swing.JOptionPane;

/**
 *
 * @author Panzi
 */
public class EditJPanel extends javax.swing.JPanel {

    /**
     * Creates new form EditJPanel
     */
    private DeliveryPackage delPackage;
    public EditJPanel() {
        initComponents();
    }

    public EditJPanel(DeliveryPackage deliveryPackage){
         initComponents();
         this.delPackage = deliveryPackage;
         displayPackageDetails();
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        custId = new javax.swing.JTextField();
        packageId = new javax.swing.JTextField();
        packageWt = new javax.swing.JTextField();
        productId = new javax.swing.JTextField();
        productName1 = new javax.swing.JTextField();
        productPrice1 = new javax.swing.JTextField();
        custName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnUpdate = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(custId, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 170, 180, 40));
        jPanel1.add(packageId, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, 180, 40));
        jPanel1.add(packageWt, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, 180, 40));
        jPanel1.add(productId, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 270, 180, 40));
        jPanel1.add(productName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 370, 180, 40));
        jPanel1.add(productPrice1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 470, 180, 40));
        jPanel1.add(custName, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 70, 180, 40));

        jLabel1.setFont(new java.awt.Font("微软雅黑", 1, 18)); // NOI18N
        jLabel1.setText("Product Price");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 480, -1, -1));

        jLabel2.setFont(new java.awt.Font("微软雅黑", 1, 18)); // NOI18N
        jLabel2.setText("Package Id");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        jLabel3.setFont(new java.awt.Font("微软雅黑", 1, 18)); // NOI18N
        jLabel3.setText("Package Weight");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        jLabel4.setFont(new java.awt.Font("微软雅黑", 1, 18)); // NOI18N
        jLabel4.setText("Product Id");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, -1, -1));

        jLabel5.setFont(new java.awt.Font("微软雅黑", 1, 18)); // NOI18N
        jLabel5.setText("Product Name");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, -1, -1));

        jLabel6.setFont(new java.awt.Font("微软雅黑", 1, 18)); // NOI18N
        jLabel6.setText("Cutomer Name");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 80, -1, -1));

        jLabel7.setFont(new java.awt.Font("微软雅黑", 1, 18)); // NOI18N
        jLabel7.setText("Customer Id");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 180, -1, -1));

        btnUpdate.setFont(new java.awt.Font("宋体", 1, 24)); // NOI18N
        btnUpdate.setText("UPDATE");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        jPanel1.add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(627, 390, 120, 50));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 690));
    }// </editor-fold>//GEN-END:initComponents

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
         String id = packageId.getText();
         String weight = packageWt.getText();
         String pId = productId.getText();
         String pName = productName1.getText();
         String pPrice = productPrice1.getText();
         String cName = custName.getText();
         String cId = custId.getText();


         this.delPackage.setPackageId(Integer.valueOf(id));
         this.delPackage.setPackageWeight(Double.valueOf(weight));

         Product product = this.delPackage.getProduct();
         product.setProductId(Integer.valueOf(pId));
         product.setProductName(pName);
         product.setPrice(Double.valueOf(pPrice));

         Customer customer = this.delPackage.getCustomer();
         customer.setCustomerId(Integer.valueOf(cId));
         customer.setFullName(cName);

        JOptionPane.showMessageDialog(null, "Saved!");
    }//GEN-LAST:event_btnUpdateActionPerformed

        public void displayPackageDetails(){
            packageId.setText(String.valueOf(this.delPackage.getPackageId()));
            packageWt.setText(String.valueOf(this.delPackage.getPackageWeight()));
            Customer customer = this.delPackage.getCustomer();
            custId.setText(String.valueOf(customer.getCustomerId()));
            custName.setText(customer.getFullName());

            Product product = this.delPackage.getProduct();
            productId.setText(String.valueOf(product.getProductId()));
            productName1.setText(product.getProductName());
            productPrice1.setText(String.valueOf(product.getPrice()));
    }



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnUpdate;
    private javax.swing.JTextField custId;
    private javax.swing.JTextField custName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField packageId;
    private javax.swing.JTextField packageWt;
    private javax.swing.JTextField productId;
    private javax.swing.JTextField productName1;
    private javax.swing.JTextField productPrice1;
    // End of variables declaration//GEN-END:variables
}
