/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.LibrarianWorkArea;

import AppSystem.AppSystem;
import Book.Author;
import Book.BookDirectory;
import Book.Genre;

/**
 *
 * @author Panzi
 */
public class AddBooksJPanel extends javax.swing.JPanel {
    private AppSystem appSystem;
    /**
     * Creates new form AddBooksJPanel
     */
    public AddBooksJPanel() {
        initComponents();
    }

    public AddBooksJPanel(AppSystem appSystem) {
        initComponents();
        this.appSystem = appSystem;

        populateDP();
    }


    public void populateDP(){
       authorBox.removeAllItems();
       genreBox.removeAllItems();
       for(Author a : this.appSystem.getAuthorDirectory().getAuthorList()){
             authorBox.addItem(a);
       }
       for(Genre g : this.appSystem.getGenreDirectory().getGenreList()){
             genreBox.addItem(g);
       }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        authorBox = new javax.swing.JComboBox();
        genreBox = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        priceTxt = new javax.swing.JTextField();
        nameTxt = new javax.swing.JTextField();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Name");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, -1, -1));

        jLabel2.setText("Rent Price");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, -1, -1));

        add(authorBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 210, 110, -1));

        add(genreBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 290, 150, -1));

        jLabel3.setText("Author");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, -1, -1));

        jLabel4.setText("Genre");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 290, -1, -1));

        btnAdd.setText("ADD");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 400, -1, -1));
        add(priceTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 140, 110, -1));
        add(nameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, 130, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        String name = nameTxt.getText();
        int renPrice = Integer.parseInt(priceTxt.getText());
        Author author = (Author)authorBox.getSelectedItem();
        Genre genre = (Genre)genreBox.getSelectedItem();
        BookDirectory bd = this.appSystem.getAllBooks();
        bd.createBook(name, author, genre);
       
    }//GEN-LAST:event_btnAddActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox authorBox;
    private javax.swing.JButton btnAdd;
    private javax.swing.JComboBox genreBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField nameTxt;
    private javax.swing.JTextField priceTxt;
    // End of variables declaration//GEN-END:variables
}
