/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI.LibrarianWorkArea;

import AppSystem.AppSystem;
import AppSystem.UserAccount;
import UI.MainJFrame;

/**
 *
 * @author Panzi
 */
public class LibrarianJFrame extends javax.swing.JFrame {

    private AppSystem appSystem;
    private UserAccount userAccount;
    /**
     * Creates new form LibrarianJFrame
     */
    public LibrarianJFrame() {
        initComponents();
    }

    public LibrarianJFrame(AppSystem appSystem, UserAccount userAccount) {
        initComponents();
        this.setVisible(true);
        
        this.appSystem = appSystem;
        this.userAccount = userAccount;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        btnRequestManage = new javax.swing.JButton();
        btnAddAuthors = new javax.swing.JButton();
        btnAddGenres = new javax.swing.JButton();
        btnAddBooks = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton4.setText("LOGOUT");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        btnRequestManage.setText("REQUESTS");
        btnRequestManage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRequestManageActionPerformed(evt);
            }
        });
        jPanel1.add(btnRequestManage, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, -1, -1));

        btnAddAuthors.setText("ADD AUTHORS");
        btnAddAuthors.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddAuthorsActionPerformed(evt);
            }
        });
        jPanel1.add(btnAddAuthors, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 20, -1, -1));

        btnAddGenres.setText("ADD GENRES");
        btnAddGenres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddGenresActionPerformed(evt);
            }
        });
        jPanel1.add(btnAddGenres, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 20, -1, -1));

        btnAddBooks.setText("ADD BOOKS");
        btnAddBooks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddBooksActionPerformed(evt);
            }
        });
        jPanel1.add(btnAddBooks, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 20, -1, -1));

        jSplitPane1.setTopComponent(jPanel1);

        getContentPane().add(jSplitPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new MainJFrame(this.appSystem, this.userAccount);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void btnRequestManageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRequestManageActionPerformed
        // TODO add your handling code here:
        jSplitPane1.setRightComponent(new RequestManagementJPanel(appSystem,userAccount));
    }//GEN-LAST:event_btnRequestManageActionPerformed

    private void btnAddAuthorsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddAuthorsActionPerformed
        // TODO add your handling code here:
        jSplitPane1.setRightComponent(new AddAuthorsJPanel(appSystem));
    }//GEN-LAST:event_btnAddAuthorsActionPerformed

    private void btnAddGenresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddGenresActionPerformed
        // TODO add your handling code here:
        jSplitPane1.setRightComponent(new AddGenresJPanel(appSystem));
    }//GEN-LAST:event_btnAddGenresActionPerformed

    private void btnAddBooksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddBooksActionPerformed
        // TODO add your handling code here:
        jSplitPane1.setRightComponent(new AddBooksJPanel(appSystem));
    }//GEN-LAST:event_btnAddBooksActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LibrarianJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LibrarianJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LibrarianJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LibrarianJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LibrarianJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddAuthors;
    private javax.swing.JButton btnAddBooks;
    private javax.swing.JButton btnAddGenres;
    private javax.swing.JButton btnRequestManage;
    private javax.swing.JButton jButton4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSplitPane jSplitPane1;
    // End of variables declaration//GEN-END:variables
}
